# Generated by Django 3.2 on 2022-08-06 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ФИО', max_length=20, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронка')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, verbose_name='Адрес')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('company', models.CharField(max_length=20, verbose_name='Компания')),
                ('postalZip', models.IntegerField(verbose_name='Почтовый индекс')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Место работы',
                'verbose_name_plural': 'Место работы',
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('acc_num', models.CharField(max_length=16)),
                ('pan', models.CharField(max_length=16)),
                ('cvv', models.IntegerField(unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'db_table': 'accounts',
            },
        ),
    ]
