# Generated by Django 3.2 on 2022-08-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='client',
            new_name='customer',
        ),
    ]
